### ISSUE TITLE
Train demo error

### ISSUE THREAD

**Issue by rylynchen** [HuangJunJie2017/BEVDet#118]
Docker build by : docker/Dockerfile
Then install by: python setup.py develop
Run command: python tools/train.py configs/bevdet/bevdet4d-r50-depth-cbgs.py
Got error:
```
root@bf150795224e:/code# python tools/train.py configs/bevdet/bevdet4d-r50-depth-cbgs.py
Traceback (most recent call last):
  File "tools/train.py", line 18, in <module>
    from mmdet3d.apis import init_random_seed, train_model
  File "/code/mmdet3d/apis/__init__.py", line 2, in <module>
    from .inference import (convert_SyncBN, inference_detector,
  File "/code/mmdet3d/apis/inference.py", line 12, in <module>
    from mmdet3d.core import (Box3DMode, CameraInstance3DBoxes, Coord3DMode,
  File "/code/mmdet3d/core/__init__.py", line 4, in <module>
    from .evaluation import *  # noqa: F401, F403
  File "/code/mmdet3d/core/evaluation/__init__.py", line 4, in <module>
    from .kitti_utils import kitti_eval, kitti_eval_coco_style
  File "/code/mmdet3d/core/evaluation/kitti_utils/__init__.py", line 2, in <module>
    from .eval import kitti_eval, kitti_eval_coco_style
  File "/code/mmdet3d/core/evaluation/kitti_utils/eval.py", line 5, in <module>
    import numba
  File "/opt/conda/lib/python3.8/site-packages/numba/__init__.py", line 43, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "/opt/conda/lib/python3.8/site-packages/numba/np/ufunc/__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "/opt/conda/lib/python3.8/site-packages/numba/np/ufunc/decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception
```
numba, numpy version:
```
numpy                    1.24.1
numba                    0.53.0
```
Anyone meet the same error ?

**Comment by myteen2** [comment]
It's a problem due to the numpy version. 
I solve that by downgrading numpy version to 1.23.5.

**Comment by rylynchen** [comment]
@myteen2 It work ! Thanks your reply.
