### ISSUE TITLE
Hi,Does anyone with me discuss the questions about the Bevdet4D to onnx and trt?

### ISSUE THREAD

**Issue by zouzouwei** [HuangJunJie2017/BEVDet#152]
I made some simple code changes but the results were not satisfactory.
such as,revise mmdet3d/models/detectors/bevdet.py , lmitate BevdetTRT add the class Bevdet4DTRT,But the effect is not ideal.
Now I would like to ask two questions,
**first question: How does this function replace in onnx**
```python
with torch.no_grad():
            feat_prev, inputs = model.module.extract_img_feat(
                inputs, pred_prev=True, img_metas=None)
```
feat_prev.shape=(8,80,128,128),represents eight frames of historical bev feature information.

**second question: can cancel  shift_feature  operation**
```python
def extract_img_feat_sequential(self, inputs, feat_prev):
        imgs, rots_curr, trans_curr, intrins = inputs[:4]
        rots_prev, trans_prev, post_rots, post_trans, bda = inputs[4:]
        bev_feat_list = []
        mlp_input = None
        
        inputs_curr = (imgs, rots_curr[0:1, ...], trans_curr[0:1, ...],
                       intrins, post_rots, post_trans, bda[0:1,
                                                           ...], None)
        bev_feat, depth = self.prepare_bev_feat(*inputs_curr)
        bev_feat_list.append(bev_feat)
        bev_feat_list.append(feat_prev.view(1, (self.num_frame - 1) * C, H, W))

        bev_feat = torch.cat(bev_feat_list, dim=1)
        x = self.bev_encoder(bev_feat)
        return [x], depth

```
I hope someone discusses this with me, I would appreciate it

**Comment by cyn-liu** [comment]
@zouzouwei  Hello:
I recently want convert `BEVDepth4D` to the `onnx` model. I have defined the `BEVDepth4DTRT` class, where parameter `(img, feat_prev,ranks_depth,ranks_feat,ranks_bev,interval_starts,interval_lengths)` is passed into the forward function of the model, but the `feature_prev` of the model cannot be obtained. 
**About your question 1**, I used 
```python
inputs = [t.cuda() for t in data['img_inputs'][0]]
with torch.no_grad():
    feat_prev, inputs = model.extract_img_feat(inputs, pred_prev=True, img_metas=None)
```
to get `feature_prev`, but encountered error 
```bash
Traceback (most recent call last):
  File "tools/convert_bevdet_to_TRT.py", line 489, in <module>
    main()
  File "tools/convert_bevdet_to_TRT.py", line 361, in main
    feat_prev, inputs = model.extract_img_feat(
  File "/workspace/BEVDet_dev2.1/mmdet3d/models/detectors/bevdet.py", line 1012, in extract_img_feat
    bev_feat, depth = self.prepare_bev_feat(*inputs_curr)
  File "/workspace/BEVDet_dev2.1/mmdet3d/models/detectors/bevdet.py", line 907, in prepare_bev_feat
    bev_feat = self.pre_process_net(bev_feat)[0]
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/BEVDet_dev2.1/mmdet3d/models/backbones/resnet.py", line 81, in forward
    x_tmp = layer(x_tmp)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/cuda11py3.9/.local/lib/python3.8/site-packages/mmdet/models/backbones/resnet.py", line 90, in forward
    out = _inner_forward(x)
  File "/home/cuda11py3.9/.local/lib/python3.8/site-packages/mmdet/models/backbones/resnet.py", line 73, in _inner_forward
    out = self.conv1(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: cuDNN error: CUDNN_STATUS_MAPPING_ERROR
```
**About your question 2**, I don't think `shift_feature` should be cancelled because alignment is key for `BEVDet4D`.

Have you solved these problems? Or do you have any ideas?
I'm looking forward to your reply  very much.

**Comment by cyn-liu** [comment]
@zouzouwei  Hello:

Recently, I want convert `BEVDepth4D` to `onnx` and `tensorRT` model, I create class `BEVDepth4DTRT`,  I use  `(img,feat_prev,ranks_depth,ranks_feat,ranks_bev,interval_starts,interval_lengths)`  as the parameters for the `forward` function of this class, but I can't get `feat_prev`.

**As your question 1,** I use 
```python
inputs = [t.cuda() for t in data['img_inputs'][0]]
with torch.no_grad():
    feat_prev, inputs = model.extract_img_feat(inputs, pred_prev=True, img_metas=None)
``` 
to obtain `feat_prev`, but I got error
```bash
Traceback (most recent call last):
  File "tools/convert_bevdet_to_TRT.py", line 489, in <module>
    main()
  File "tools/convert_bevdet_to_TRT.py", line 361, in main
    feat_prev, inputs = model.extract_img_feat(
  File "/workspace/BEVDet_dev2.1/mmdet3d/models/detectors/bevdet.py", line 1012, in extract_img_feat
    bev_feat, depth = self.prepare_bev_feat(*inputs_curr)
  File "/workspace/BEVDet_dev2.1/mmdet3d/models/detectors/bevdet.py", line 907, in prepare_bev_feat
    bev_feat = self.pre_process_net(bev_feat)[0]
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/BEVDet_dev2.1/mmdet3d/models/backbones/resnet.py", line 81, in forward
    x_tmp = layer(x_tmp)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/cuda11py3.9/.local/lib/python3.8/site-packages/mmdet/models/backbones/resnet.py", line 90, in forward
    out = _inner_forward(x)
  File "/home/cuda11py3.9/.local/lib/python3.8/site-packages/mmdet/models/backbones/resnet.py", line 73, in _inner_forward
    out = self.conv1(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: cuDNN error: CUDNN_STATUS_MAPPING_ERROR
```

**As your question 2,** I think alignment is the key to `BEVDet4D`, so I didn't cancel `shift_feature`.

Have you solved these problems? Or do you have any suggestions?
I'm looking forward to your reply soon.
