### ISSUE TITLE
RuntimeError: shape '[80, 1, 1, 1]' is invalid for input of size 27

### ISSUE THREAD

**Issue by cyn-liu** [HuangJunJie2017/BEVDet#202]
Hello: 
When I evaluated the `BEVDet-R50-4D-Depth-CBGS` model, I received the following error:
```
/home/cuda11py3.9/.local/lib/python3.8/site-packages/mmdet/utils/setup_env.py:38: UserWarning: Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
/home/cuda11py3.9/.local/lib/python3.8/site-packages/mmdet/utils/setup_env.py:48: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
/home/cuda11py3.9/.local/lib/python3.8/site-packages/mmdet/models/backbones/resnet.py:401: UserWarning: DeprecationWarning: pretrained is deprecated, please use "init_cfg" instead
  warnings.warn('DeprecationWarning: pretrained is deprecated, '
load checkpoint from local path: ./checkpoints/bevdet4d-r50-depth-cbgs.pth
Traceback (most recent call last):
  File "tools/test.py", line 267, in <module>
    main()
  File "tools/test.py", line 221, in main
    model = fuse_conv_bn(model)
  File "/home/cuda11py3.9/.local/lib/python3.8/site-packages/mmcv/cnn/utils/fuse_conv_bn.py", line 58, in fuse_conv_bn
    fuse_conv_bn(child)
  File "/home/cuda11py3.9/.local/lib/python3.8/site-packages/mmcv/cnn/utils/fuse_conv_bn.py", line 58, in fuse_conv_bn
    fuse_conv_bn(child)
  File "/home/cuda11py3.9/.local/lib/python3.8/site-packages/mmcv/cnn/utils/fuse_conv_bn.py", line 49, in fuse_conv_bn
    fused_conv = _fuse_conv_bn(last_conv, child)
  File "/home/cuda11py3.9/.local/lib/python3.8/site-packages/mmcv/cnn/utils/fuse_conv_bn.py", line 22, in _fuse_conv_bn
    factor.reshape([conv.out_channels, 1, 1, 1]))
RuntimeError: shape '[80, 1, 1, 1]' is invalid for input of size 27
```
我执行的指令是：
```bash
python tools/test.py ./configs/bevdet/bevdet4d-r50-depth-cbgs.py ./checkpoints/bevdet4d-r50-depth-cbgs.pth --fuse-conv-bn --gpu-id 0 --eval bbox
```
我没有对代码做更改，用类似的指令对`BEVDet-R50`，`BEVDet-R50-CBGS`，`BEVDet-R50-4D-CBGS`都可以成功得到评估结果，有人知道报错的原因吗？感谢回复！

**Comment by HuangJunJie2017** [comment]
@cyn-liu the function fuse_conv_bn try to fuse the conv and bn defined here:
https://github.com/HuangJunJie2017/BEVDet/blob/126ad946ee69ae9a1a59c5d3f71f79da5edfbd73/mmdet3d/models/necks/view_transformer.py#L472
 
you can avoid this error by simply change the order them from 
```
        self.context_conv = nn.Conv2d(
            mid_channels, context_channels, kernel_size=1, stride=1, padding=0)
        self.bn = nn.BatchNorm1d(27)
```
to 
```
        self.bn = nn.BatchNorm1d(27)
        self.context_conv = nn.Conv2d(
            mid_channels, context_channels, kernel_size=1, stride=1, padding=0)
```

**Comment by cyn-liu** [comment]
感谢你的回复，程序可以成功运行了！！！
