### ISSUE TITLE
get_flops.py

### ISSUE THREAD

**Issue by aqr1961** [HuangJunJie2017/BEVDet#213]
黄博士您好，请问，对于get_flpos.py中的construct_input函数  具体应该如何进行修改，以测量其他配置（bevdet4d-r50-depth-cbgs）的计算量和 参数数量？

**Comment by HuangJunJie2017** [comment]
@aqr1961  get_flops.py has been updated to adapt to dev2.1
bevdet4d-r50-depth-cbgs with
Flops: 676.01 GFLOPs
Params: 74.9 M

**Comment by aqr1961** [comment]
Traceback (most recent call last):
  File "tools/analysis_tools/get_flops.py", line 106, in <module>
    main()
  File "tools/analysis_tools/get_flops.py", line 95, in main
    flops, params = get_model_complexity_info(
  File "/root/anaconda3/envs/openmmlab2/lib/python3.8/site-packages/mmcv/cnn/utils/flops_counter.py", line 94, in get_model_complexity_info
    _ = flops_model(**input)
  File "/root/anaconda3/envs/openmmlab2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/etc/BEVDet-dev2.1/mmdet3d/models/detectors/bevdet.py", line 195, in forward_dummy
    img_feats, _, _ = self.extract_feat(
  File "/etc/BEVDet-dev2.1/mmdet3d/models/detectors/bevdet.py", line 84, in extract_feat
    img_feats, depth = self.extract_img_feat(img, img_metas, **kwargs)
  File "/etc/BEVDet-dev2.1/mmdet3d/models/detectors/bevdet.py", line 76, in extract_img_feat
    img = self.prepare_inputs(img)
  File "/etc/BEVDet-dev2.1/mmdet3d/models/detectors/bevdet.py", line 61, in prepare_inputs
    sensor2egos = sensor2egos.view(B, N, 4, 4)
RuntimeError: shape '[1, 6, 4, 4]' is invalid for input of size 54
黄博士您好，我在v2.1版本中运行遇到了这样的错误  但是在v2.0中却可以正常运行，两个版本使用相同的环境。我感到十分疑惑。谢谢您的回复。

**Comment by HuangJunJie2017** [comment]
@aqr1961 check the difference between these two branches or pull the latest dev2.1 branch

**Comment by aqr1961** [comment]
另外 对于mmdeploy库的安装，想向您请教如下问题，我在您的github主页下载了这个库 并运行pip -r requirements.txt进行安装，之后根据get_started.md文件安装了install inference engine: TensorRT.但是遇到了下面的错误：
Traceback (most recent call last):
  File "tools/convert_bevdet_to_TRT.py", line 5, in <module>
    from mmdeploy.backend.tensorrt.utils import save, search_cuda_version
ModuleNotFoundError: No module named 'mmdeploy.backend'

**Comment by aqr1961** [comment]
> @aqr1961 check the difference between these two branches or pull the latest dev2.1 branch

非常感谢

**Comment by HuangJunJie2017** [comment]
> 另外 对于mmdeploy库的安装，想向您请教如下问题，我在您的github主页下载了这个库 并运行pip -r requirements.txt进行安装，之后根据get_started.md文件安装了install inference engine: TensorRT.但是遇到了下面的错误： Traceback (most recent call last): File "tools/convert_bevdet_to_TRT.py", line 5, in from mmdeploy.backend.tensorrt.utils import save, search_cuda_version ModuleNotFoundError: No module named 'mmdeploy.backend'

Please refer to the official mmdeploy from openmmlab for problems in installing mmdeploy

**Comment by aqr1961** [comment]
> @aqr1961 get_flops.py has been updated to adapt to dev2.1 bevdet4d-r50-depth-cbgs with Flops: 676.01 GFLOPs Params: 74.9 M

**Comment by aqr1961** [comment]
黄博士您好 我经检查发现，两个分支版本中  get_flpos.py部分代码  完全一致，但是在config文件中 对于网络的通道数等设置并不一致，如果因为网络结构引起的 输入数据不匹配，是否需要对get_flpos.py中产生数据的部分进行修改呢？ 我使用这个环境可以正常的进行推理，我认为应该不是环境问题导致的错误。

**Comment by HuangJunJie2017** [comment]
@aqr1961  get_flops has been modified in dev2.1, please pull the latest code
https://github.com/HuangJunJie2017/BEVDet/commit/c0d20ffe0b98ce8dcee5a6c02d755cc1a751b612
