### ISSUE TITLE
KeyError: 'ann_info'

### ISSUE THREAD

**Issue by odd2022** [HuangJunJie2017/BEVDet#298]
Hello, I am trying to prepare my dataset by typing the cmd: 
`python tools/create_data.py  --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes`
as suggested in the tutorial but i get this error: 

`[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 81/81, 7.8 task/s, elapsed: 10s, ETA:     0s
Create GT Database of NuScenesDataset
[                                                  ] 0/323, elapsed: 0s, ETA:{'sample_idx': 'ca9a282c9e77460f8360f564131a8af5', 'pts_filename': './data/nuscenes/samples/LIDAR_TOP/n015-2018-07-24-11-22-45+0800__LIDAR_TOP__1532402927647951.pcd.bin', 'sweeps': [], 'timestamp': 1532402927.647951, 'img_fields': [], 'bbox3d_fields': [], 'pts_mask_fields': [], 'pts_seg_fields': [], 'bbox_fields': [], 'mask_fields': [], 'seg_fields': [], 'box_type_3d': <class 'mmdet3d.core.bbox.structures.lidar_box3d.LiDARInstance3DBoxes'>, 'box_mode_3d': <Box3DMode.LIDAR: 0>}
Traceback (most recent call last):
  File "tools/create_data.py", line 267, in <module>
    nuscenes_data_prep(
  File "tools/create_data.py", line 89, in nuscenes_data_prep
    create_groundtruth_database(dataset_name, root_path, info_prefix,
  File "HoP/tools/data_converter/create_gt_database.py", line 241, in create_groundtruth_database
    example = dataset.pipeline(input_dict)
  File "HoP/mmdet3d/datasets/pipelines/compose.py", line 49, in __call__
    data = t(data)
  File "HoP/mmdet3d/datasets/pipelines/loading.py", line 682, in __call__
    results = self._load_bboxes_3d(results)
  File "HoP/mmdet3d/datasets/pipelines/loading.py", line 577, in _load_bboxes_3d
    results['gt_bboxes_3d'] = results['ann_info']['gt_bboxes_3d']
KeyError: 'ann_info'
`
Has anyone faced this problem yet ? Thank you

**Comment by GG-Bonds** [comment]
我也是

**Comment by yuzuki612166** [comment]
me too, have you solved it?

**Comment by jasper-knight** [comment]
something is wrong when you process dataset . if you use nuscenes v1.0-mini like me.  before running 'python tools/create_data_bevdet.py' , you need replace nuscens version in two place like below:

<img width="784" height="481" alt="Image" src="https://github.com/user-attachments/assets/40ea275d-c4f9-4307-8799-716abd4580df" />

<img width="717" height="443" alt="Image" src="https://github.com/user-attachments/assets/885ac34c-a238-434b-8870-b9a851e8f568" />
