### ISSUE TITLE
[dev3.0]How to get bevdetv5-nuscenes_infos_train.pkl

### ISSUE THREAD

**Issue by zzpbigpeng** [HuangJunJie2017/BEVDet#337]
# RUN：
python tools/train.py ./configs/dal/dal-tiny.py

# ERROR：
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/share/code/BEVDet-dev3.0/mmdet3d/datasets/nuscenes_dataset.py", line 145, in __init__
    super().__init__(
  File "/share/code/BEVDet-dev3.0/mmdet3d/datasets/custom_3d.py", line 88, in __init__
    self.data_infos = self.load_annotations(open(local_path, 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: 'data/nuscenes/bevdetv5-nuscenes_infos_train.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 277, in <module>
    main()
  File "tools/train.py", line 226, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/share/code/BEVDet-dev3.0/mmdet3d/datasets/builder.py", line 40, in build_dataset
    dataset = CBGSDataset(build_dataset(cfg['dataset'], default_args))
  File "/share/code/BEVDet-dev3.0/mmdet3d/datasets/builder.py", line 44, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
FileNotFoundError: NuScenesDataset: [Errno 2] No such file or directory: 'data/nuscenes/bevdetv5-nuscenes_infos_train.pkl'

# ANALYZE：
I am missing the bevdetv5-nuscenes_infos_train.pkl.
I downloaded version 3.0 of the code and used the script you provided to generate the corresponding pkl file for nuscenes, but what was generated was bevdetv3-nuscenes_infos_train.pkl.
_I want to know how to generate bevdetv5-nuscenes_infos_train.pkl?_

**Comment by zhangchuang-zc** [comment]
I have the same issus, have you solve this?

**Comment by yuezhao1** [comment]
@zzpbigpeng Have you solved this problem yet？

**Comment by Wansit99** [comment]
估计是作者打错了 我查阅了下bevdet的config 都是bevdetv3-nuscenes

**Comment by Wansit99** [comment]
I think the author made a typo. I checked the config for bevdet and it's all bevdetv3-nuscenes.
