### ISSUE TITLE
FP16 Training

### ISSUE THREAD

**Issue by Divadi** [HuangJunJie2017/BEVDet#50]
Hi, I was wondering if you have had any success with incorporating FP16?

I have done some experiments, but the large value of the heatmap loss (>10k) at beginning seems to make it difficult. Further, training randomly nan's hundreds of iterations in.

Also, what is "'/mnt/cfs/algorithm/junjie.huang/models/resnet50-0676ba61.pth'" in the recently released R50 config? Is this just the torchvision pretrained model that can be loaded via checkpoint='torchvision://resnet50'?

**Comment by HuangJunJie2017** [comment]
@Divadi 
It seems that the DNN is too deep to apply FP16(both torch/APX will lead to nan)
you are right, I will fix this later with checkpoint='torchvision://resnet50'

**Comment by zehuichen123** [comment]
Hi, I am also trying with FP16 in the BEVDet codebase, but failed with loss unconvergence. However, I notice that BEVDepth adopt fp16 in its code.

**Comment by HuangJunJie2017** [comment]
@Divadi @zehuichen123 A good news is that I have successfully trained bevdet4d-r50 with fp16. The inference results is even a bit higher than that trained with FP32.
fp16:
mAP: 0.3274
mATE: 0.6791
mASE: 0.2797
mAOE: 0.5158
mAVE: 0.3552
mAAE: 0.2060
NDS: 0.4601
Eval time: 175.8s

**Comment by zehuichen123** [comment]
wow! could you share how you successfully train your model?

**Comment by HuangJunJie2017** [comment]
@zehuichen123 just use this~
fp16 = dict(loss_scale='dynamic')
and add @force_fp32() before def shift_feature(self, input, trans, rots): 
I will push these modification soon

**Comment by zehuichen123** [comment]
cool~ I will give it a try! thanks!

**Comment by HuangJunJie2017** [comment]
It seems that FP16 can only be used when the image view backbone is not swin transformer

**Comment by cyn-liu** [comment]
HI @HuangJunJie2017 
I tried using fp16 to train BEVDet-dev2.1 `bevdet-r50-cbgs.py`, but the loss has always been `Nan` eventually terminated abnormally, do you know why? 

I only changed `#fp16 = dict(loss_scale='dynamic')` to `fp16 = dict(loss_scale='dynamic')` in `bevdet-r50-cbgs.py`

my log :
```bash
$nohup tools/dist_train.sh configs/bevdet/bevdet-r50-cbgs.py 2 > mytrain_r50-fp16_log.txt 2>&1 &
2023-06-15 04:03:40,870 - mmdet - INFO - Epoch [1][50/3862]	lr: 4.915e-05, eta: 3 days, 22:56:26, time: 4.428, data_time: 1.900, memory: 10657, task0.loss_xy: 0.2820, task0.loss_z: 0.3374, task0.loss_whl: 0.7133, task0.loss_yaw: 0.3525, task0.loss_vel: 0.0843, task0.loss_heatmap: nan, loss: nan, grad_norm: nan
2023-06-15 04:05:44,778 - mmdet - INFO - Epoch [1][100/3862]	lr: 9.910e-05, eta: 3 days, 1:59:42, time: 2.479, data_time: 0.368, memory: 10657, task0.loss_xy: 0.2815, task0.loss_z: 0.3439, task0.loss_whl: 0.7107, task0.loss_yaw: 0.3526, task0.loss_vel: 0.0884, task0.loss_heatmap: nan, loss: nan, grad_norm: nan
2023-06-15 04:07:49,798 - mmdet - INFO - Epoch [1][150/3862]	lr: 1.491e-04, eta: 2 days, 19:08:44, time: 2.500, data_time: 0.140, memory: 10658, task0.loss_xy: 0.2809, task0.loss_z: 0.3409, task0.loss_whl: 0.7121, task0.loss_yaw: 0.3495, task0.loss_vel: 0.0868, task0.loss_heatmap: nan, loss: nan, grad_norm: nan
2023-06-15 04:10:20,007 - mmdet - INFO - Epoch [1][200/3862]	lr: 1.990e-04, eta: 2 days, 18:23:51, time: 3.004, data_time: 0.428, memory: 10658, task0.loss_xy: 0.2798, task0.loss_z: 0.3368, task0.loss_whl: 0.7023, task0.loss_yaw: 0.3505, task0.loss_vel: 0.0852, task0.loss_heatmap: nan, loss: nan, grad_norm: nan
2023-06-15 04:13:08,175 - mmdet - INFO - Epoch [1][250/3862]	lr: 2.000e-04, eta: 2 days, 19:28:09, time: 3.363, data_time: 1.301, memory: 10658, task0.loss_xy: 0.2803, task0.loss_z: 0.3464, task0.loss_whl: 0.7115, task0.loss_yaw: 0.3507, task0.loss_vel: 0.0842, task0.loss_heatmap: nan, loss: nan, grad_norm: nan
2023-06-15 04:15:39,932 - mmdet - INFO - Epoch [1][300/3862]	lr: 2.000e-04, eta: 2 days, 18:59:57, time: 3.035, data_time: 0.828, memory: 10658, task0.loss_xy: 0.2796, task0.loss_z: 0.3419, task0.loss_whl: 0.7134, task0.loss_yaw: 0.3507, task0.loss_vel: 0.0839, task0.loss_heatmap: nan, loss: nan, grad_norm: nan
2023-06-15 04:18:05,268 - mmdet - INFO - Epoch [1][350/3862]	lr: 2.000e-04, eta: 2 days, 18:15:35, time: 2.907, data_time: 0.375, memory: 10658, task0.loss_xy: 0.2809, task0.loss_z: 0.3422, task0.loss_whl: 0.7125, task0.loss_yaw: 0.3537, task0.loss_vel: 0.0869, task0.loss_heatmap: nan, loss: nan, grad_norm: nan
2023-06-15 04:20:42,324 - mmdet - INFO - Epoch [1][400/3862]	lr: 2.000e-04, eta: 2 days, 18:19:12, time: 3.141, data_time: 0.123, memory: 10658, task0.loss_xy: 0.2808, task0.loss_z: 0.3406, task0.loss_whl: 0.7151, task0.loss_yaw: 0.3519, task0.loss_vel: 0.0859, task0.loss_heatmap: nan, loss: nan, grad_norm: nan
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 600 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 1 (pid: 601) of binary: /opt/conda/bin/python
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 715, in run
    elastic_launch(
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
====================================================
tools/train.py FAILED
----------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
----------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-06-15_04:23:55
  host      : ubuntu1804
  rank      : 1 (local_rank: 1)
  exitcode  : -9 (pid: 601)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 601
====================================================
```
