### ISSUE TITLE
当模型验证时会报错 RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by shuowang666** [HuangJunJie2017/BEVDet#64]
Traceback (most recent call last):
  File "./tools/train.py", line 226, in <module>
    main()
  File "./tools/train.py", line 222, in main
    meta=meta)
  File "/home/ma-user/modelarts/user-job-dir/BEVDet/mmdet3d/apis/train.py", line 35, in train_model
    meta=meta)
  File "/home/ma-user/open-mmlab/mmdetection/mmdet/apis/train.py", line 177, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/ma-user/open-mmlab/mmcv/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/ma-user/open-mmlab/mmcv/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/home/ma-user/open-mmlab/mmcv/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/ma-user/open-mmlab/mmcv/mmcv/runner/hooks/evaluation.py", line 267, in after_train_epoch
    self._do_evaluate(runner)
  File "/home/ma-user/open-mmlab/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 54, in _do_evaluate
    gpu_collect=self.gpu_collect)
  File "/home/ma-user/open-mmlab/mmdetection/mmdet/apis/test.py", line 98, in multi_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/root/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 886, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/root/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ma-user/open-mmlab/mmcv/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/home/ma-user/modelarts/user-job-dir/BEVDet/mmdet3d/models/detectors/base.py", line 61, in forward
    return self.forward_test(**kwargs)
  File "/home/ma-user/modelarts/user-job-dir/BEVDet/mmdet3d/models/detectors/bevdet.py", line 123, in forward_test
    return self.simple_test(points[0], img_metas[0], img_inputs[0], **kwargs)
  File "/home/ma-user/modelarts/user-job-dir/BEVDet/mmdet3d/models/detectors/bevdet.py", line 354, in simple_test
    img_feats, _, _ = self.extract_feat(points, img=img, img_metas=img_metas)
  File "/home/ma-user/modelarts/user-job-dir/BEVDet/mmdet3d/models/detectors/bevdet.py", line 347, in extract_feat
    img_feats, depth = self.extract_img_feat(img, img_metas)
  File "/home/ma-user/modelarts/user-job-dir/BEVDet/mmdet3d/models/detectors/bevdet.py", line 388, in extract_img_feat
    x, depth = self.img_view_transformer([x] + img[1:])
  File "/root/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ma-user/modelarts/user-job-dir/BEVDet/mmdet3d/models/necks/view_transformer.py", line 347, in forward
    bev_feat = self.voxel_pooling_accelerated(rots, trans, intrins, post_rots, post_trans, volume)
  File "/home/ma-user/modelarts/user-job-dir/BEVDet/mmdet3d/models/necks/view_transformer.py", line 244, in voxel_pooling_accelerated
    x = x[idx]
RuntimeError: CUDA error: device-side assert triggered
terminate called after throwing an instance of 'c10::CUDAError'
  what():  CUDA error: device-side assert triggered
Exception raised from create_event_internal at ../c10/cuda/CUDACachingAllocator.cpp:1211 (most recent call first):

模型可以正常训练，但是当训练到指定epoch进行eval时，就会报下面的错误，请问一下这是什么原因呢

**Comment by HuangJunJie2017** [comment]
@shuowang666 Try not to train bevdet with acceleration~ 
use https://github.com/HuangJunJie2017/BEVDet/blob/master/configs/bevdet/bevdet-sttiny.py instead for training~
acceleration only can be used in testing ~
