### ISSUE TITLE
Error: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by Daniel-xsy** [HuangJunJie2017/BEVDet#87]
## **Checklist**
I have searched related issues but cannot get the expected help.

##  **Describe the bug**
When I'm trying to inference the BEVDet and BEVDepth models, an error raised In `bev_pool` function at [bev_pool.py](https://github.com/HuangJunJie2017/BEVDet/blob/master/mmdet3d/ops/bev_pool/bev_pool.py)
```
95    x = QuickCumsumCuda.apply(feats, coords, ranks, B, D, H, W)
96    x = x.permute(0, 4, 1, 2, 3).contiguous()
```
`RuntimeError: CUDA error: no kernel image is available for execution on the device`. However, **when I use debug line by line and set a breakpoint in the line96 the error just disappear!**

I do this several times and it **works just fine** as shown below:
```
[>                                                 ] 3/81, 0.0 task/s, elapsed: 365s, ETA:  9496s
```
However, when I delete the breakpoint and click `continue to run`, the error show up again.

##  **Reproduction**
1. What command or script did you run?
```
bash tools/dist_test.sh configs/bevdet/bevdet-r50.py models/bevdet/bevdet-r50.pth 8
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?

Nothing has been modified.

3. What dataset did you use?

nuscenes-mini v1.0 datasets

##  **Environment**

1. Please run `python mmdet3d/utils/collect_env.py` to collect necessary environment infomation and paste it here.
```
sys.platform: linux
Python: 3.7.13 (default, Mar 29 2022, 02:18:16) [GCC 7.5.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: NVIDIA RTX A5000
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.0_bu.TC445_37.28540450_0
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.9.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.5
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - Built with CUDA Runtime 11.2
  - NVCC architecture flags: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_50,code=compute_50
  - CuDNN 8.4.1  (built against CUDA 11.6)
    - Built with CuDNN 8.2.1
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.2, CUDNN_VERSION=8.2.1, CXX_COMPILER=/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1627802491209/_build_env/bin/x86_64-conda-linux-gnu-c++, CXX_FLAGS=-std=c++14 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/conda/feedstock_root/build_artifacts/pytorch-recipe_1627802491209/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1627802491209/work=/usr/local/src/conda/pytorch-1.9.0 -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1627802491209/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh=/usr/local/src/conda-prefix -I/usr/local/cuda/include -Wno-deprecated-declarations -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=1, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.10.0a0
OpenCV: 4.6.0
MMCV: 1.3.13
MMCV Compiler: GCC 9.4
MMCV CUDA Compiler: 11.0
MMDetection: 2.14.0
MMSegmentation: 0.14.1
MMDetection3D: 0.17.2+9f858b4
```

2. You may add addition that may be helpful for locating the problem

I install PyTorch using the following commands, the version is just as suggested in [getting_started.md](https://github.com/HuangJunJie2017/BEVDet/blob/master/docs/getting_started.md)
```
conda install pytorch==1.9.0 torchvision==0.10.0 torchaudio==0.9.0 cudatoolkit=11.3 -c pytorch -c conda-forge
```

##  **Error traceback**

```
Traceback (most recent call last):
  File "tools/test.py", line 221, in <module>
    main()
  File "tools/test.py", line 198, in main
    args.gpu_collect)
  File "/usr/local/anaconda3/envs/bevdet/lib/python3.7/site-packages/mmdet/apis/test.py", line 97, in multi_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/usr/local/anaconda3/envs/bevdet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/anaconda3/envs/bevdet/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 799, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/usr/local/anaconda3/envs/bevdet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/anaconda3/envs/bevdet/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/home/cihangxie/shaoyuan/BEV-Attack/zoo/BEVDet/mmdet3d/models/detectors/base.py", line 61, in forward
    return self.forward_test(**kwargs)
  File "/home/cihangxie/shaoyuan/BEV-Attack/zoo/BEVDet/mmdet3d/models/detectors/bevdet.py", line 122, in forward_test
    return self.simple_test(points[0], img_metas[0], img_inputs[0], **kwargs)
  File "/home/cihangxie/shaoyuan/BEV-Attack/zoo/BEVDet/mmdet3d/models/detectors/bevdet.py", line 138, in simple_test
    img_feats, _ = self.extract_feat(points, img=img, img_metas=img_metas)
  File "/home/cihangxie/shaoyuan/BEV-Attack/zoo/BEVDet/mmdet3d/models/detectors/bevdet.py", line 45, in extract_feat
    img_feats = self.extract_img_feat(img, img_metas)
  File "/home/cihangxie/shaoyuan/BEV-Attack/zoo/BEVDet/mmdet3d/models/detectors/bevdet.py", line 39, in extract_img_feat
    x = self.img_view_transformer([x] + img[1:])
  File "/usr/local/anaconda3/envs/bevdet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/cihangxie/shaoyuan/BEV-Attack/zoo/BEVDet/mmdet3d/models/necks/view_transformer.py", line 273, in forward
    bev_feat = self.voxel_pooling(geom, volume)
  File "/home/cihangxie/shaoyuan/BEV-Attack/zoo/BEVDet/mmdet3d/models/necks/view_transformer.py", line 168, in voxel_pooling
    self.nx[1])
  File "/home/cihangxie/shaoyuan/BEV-Attack/zoo/BEVDet/mmdet3d/ops/bev_pool/bev_pool.py", line 97, in bev_pool
    x = x.permute(0, 4, 1, 2, 3).contiguous()
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Comment by zhanghaozhe23** [comment]
I have the same problem. Have you solved it

**Comment by Daniel-xsy** [comment]
> I have the same problem. Have you solved it

No, I choose to use the CPU version of bev pool, which might be slower. You can adjust to CPU version by modifying the corresponding config file.

**Comment by daxiongpro** [comment]
hi, I have the same problem. Have you solved it?

**Comment by SeaBird-Go** [comment]
@Daniel-xsy , I also have this problem. How to choose to use the CPU version of bev pool? And how about the training speed decrease?
