### ISSUE TITLE
calculate FLOPs  error

### ISSUE THREAD

**Issue by bruce1408** [HuangJunJie2017/BEVDet#91]
when i use get_flops.py file to calculate bevdepth models FLOPs, the error occured as follows:
```
Traceback (most recent call last):
  File "tools/analysis_tools/get_flops.py", line 110, in <module>
    main()
  File "tools/analysis_tools/get_flops.py", line 100, in main
    flops, params = get_model_complexity_info(model, input_shape, input_constructor=construct_input)
  File "/home/anaconda3/envs/torch1.9.0/lib/python3.7/site-packages/mmcv/cnn/utils/flops_counter.py", line 92, in get_model_complexity_info
    _ = flops_model(**input)
  File "/home/anaconda3/envs/torch1.9.0/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1120, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/new_bevdet/BEVDet/mmdet3d/models/detectors/bevdet.py", line 147, in forward_dummy
    img_feats, _ = self.extract_feat(points, img=img_inputs, img_metas=img_metas)
  File "/home/new_bevdet/BEVDet/mmdet3d/models/detectors/bevdet.py", line 347, in extract_feat
    img_feats, depth = self.extract_img_feat(img, img_metas)
  File "/home/new_bevdet/BEVDet/mmdet3d/models/detectors/bevdet.py", line 389, in extract_img_feat
    x, depth = self.img_view_transformer([x] + img[1:])
  File "/home/anaconda3/envs/torch1.9.0/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/new_bevdet/BEVDet/mmdet3d/models/necks/view_transformer.py", line 324, in forward
    x, rots, trans, intrins, post_rots, post_trans, depth_gt = input
ValueError: not enough values to unpack (expected 7, got 6)
```
and i try to use bevdepth4d, the same error is reported, while the other model like bevdet, bevdet4d does not report an error

**Comment by HuangJunJie2017** [comment]
@bruce1408  modify the input by adding depth_gt as 'None' like this:
def construct_input(input_shape):
    rot = torch.eye(3).float().cuda().view(1,3,3)
    rot = torch.cat([rot for _ in range(6)],axis=0).view(1,6,3,3)

    input =dict(img_inputs=[
        torch.ones(()).new_empty(
                (1, 6, 3, *input_shape)).cuda(),
        rot,
        torch.ones((1, 6, 3)).cuda(),
        rot,
        rot,
        torch.ones((1, 6, 3)).cuda(), None])
    return input
https://github.com/HuangJunJie2017/BEVDet/blob/2919b997c8fb2cb4737fd844200936ef04900d37/tools/analysis_tools/get_flops.py#L42

**Comment by bruce1408** [comment]
> 
 I run it, and there are errors in this place **bevdet.py**
 
![image](https://user-images.githubusercontent.com/22500511/201023850-84679410-2496-46c9-9c82-1986e6c9b5e7.png)

 After changing it, it will work.
